#!/usr/bin/env bash
#MISE description="Upload LessPaper.ipa"
set -euo pipefail

AUTH_KEY_ID="$(fnox get ALTOOL_KEY_ID)"
AUTH_KEY_ISSUER="$(fnox get ALTOOL_ISSUER_ID)"

TMP_DIR=/private$(mktemp -d)
AUTH_KEY_PATH="$TMP_DIR/AuthKey_${AUTH_KEY_ID}.p8"

trap "rm -rf $TMP_DIR" EXIT # Delete on exit

fnox get ALTOOL_AUTH_KEY | base64 -d > "$AUTH_KEY_PATH"

fnox exec -- xcrun altool --upload-app \
  --type ios \
  --file "build/LessPaper.ipa" \
  --p8-file-path "$AUTH_KEY_PATH" \
  --api-key "$AUTH_KEY_ID" \
  --api-issuer 69a6de6e-9f57-47e3-e053-5b8c7c11a4d1 \
  --show-progress
