import Foundation
import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "LessPaper",
    projects: ["."],
    generationOptions: .options(
        // CI runs this synthesised scheme rather than any of the per-module ones, and its coverage
        // is off unless asked for - which is why every `coverage: true` in Module+Schemes.swift has
        // never produced a line of coverage data on a CI run.
        //
        // `.relevant` rather than naming the coverage targets: `tuist test <scheme>` trims the
        // graph to that scheme's dependencies, but emits this scheme anyway, so an explicit list
        // names targets that no longer exist and generation dies on its own lint before running a
        // test. Tuist's own set is the 28 modules plus ShareApp.app, which is never listed because
        // ShareAppTests runs in the UI job.
        autogeneratedWorkspaceSchemes: .enabled(
            codeCoverageMode: .relevant
        ),
        lastXcodeUpgradeCheck: Version(26, 5, 0)
    )
)
