import Foundation

public enum Permission: String, CaseIterable, Codable, Equatable, Sendable {
    case addApplicationConfiguration = "add_applicationconfiguration"
    case addCorrespondent = "add_correspondent"
    case addCustomField = "add_customfield"
    case addDocument = "add_document"
    case addDocumentType = "add_documenttype"
    case addGroup = "add_group"
    case addLogEntry = "add_logentry"
    case addMailAccount = "add_mailaccount"
    case addMailRule = "add_mailrule"
    case addNote = "add_note"
    case addPaperlessTask = "add_paperlesstask"
    case addSavedView = "add_savedview"
    case addShareLink = "add_sharelink"
    case addStoragePath = "add_storagepath"
    case addTag = "add_tag"
    case addUiSettings = "add_uisettings"
    case addUser = "add_user"
    case addWorkflow = "add_workflow"
    case changeApplicationConfiguration = "change_applicationconfiguration"
    case changeCorrespondent = "change_correspondent"
    case changeCustomfield = "change_customfield"
    case changeDocument = "change_document"
    case changeDocumentType = "change_documenttype"
    case changeGroup = "change_group"
    case changeLogEntry = "change_logentry"
    case changeMailAccount = "change_mailaccount"
    case changeMailRule = "change_mailrule"
    case changeNote = "change_note"
    case changePaperlessTask = "change_paperlesstask"
    case changeSavedView = "change_savedview"
    case changeShareLink = "change_sharelink"
    case changeStoragePath = "change_storagepath"
    case changeTag = "change_tag"
    case changeUiSettings = "change_uisettings"
    case changeUser = "change_user"
    case changeWorkflow = "change_workflow"
    case deleteApplicationConfiguration = "delete_applicationconfiguration"
    case deleteCorrespondent = "delete_correspondent"
    case deleteCustomField = "delete_customfield"
    case deleteDocument = "delete_document"
    case deleteDocumentType = "delete_documenttype"
    case deleteGroup = "delete_group"
    case deleteLogEntry = "delete_logentry"
    case deleteMailAccount = "delete_mailaccount"
    case deleteMailRule = "delete_mailrule"
    case deleteNote = "delete_note"
    case deletePaperlessTask = "delete_paperlesstask"
    case deleteSavedView = "delete_savedview"
    case deleteShareLink = "delete_sharelink"
    case deleteStoragePath = "delete_storagepath"
    case deleteTag = "delete_tag"
    case deleteUiSettings = "delete_uisettings"
    case deleteUser = "delete_user"
    case deleteWorkflow = "delete_workflow"
    case viewApplicationConfiguration = "view_applicationconfiguration"
    case viewCorrespondent = "view_correspondent"
    case viewCustomField = "view_customfield"
    case viewDocument = "view_document"
    case viewDocumentType = "view_documenttype"
    case viewGroup = "view_group"
    case viewLogEntry = "view_logentry"
    case viewMailAccount = "view_mailaccount"
    case viewMailRule = "view_mailrule"
    case viewNote = "view_note"
    case viewPaperlessTask = "view_paperlesstask"
    case viewSavedView = "view_savedview"
    case viewShareLink = "view_sharelink"
    case viewStoragePath = "view_storagepath"
    case viewTag = "view_tag"
    case viewUiSettings = "view_uisettings"
    case viewUser = "view_user"
    case viewWorkflow = "view_workflow"
}

extension Permission: Comparable {
    public static func < (lhs: Permission, rhs: Permission) -> Bool {
        lhs.rawValue < rhs.rawValue
    }
}
