#!/usr/bin/env bash
#MISE description="Update tools via mise"
set -e
tools=$(mise outdated --local | awk '{print $1}' | tr '\n' ' ')
echo "outdated tools: $tools"
if [ -n "$tools" ]; then
    mise upgrade $tools --bump
fi
