#!/usr/bin/env bash
#MISE description="Show difference between all modified snapshot images"
#USAGE flag "--path <path>" help="Path to snapshot images" default="Snapshots/**/*.png"
#USAGE flag "--parent <parent>" help="Parent git branch/ref to compare to" default="origin/main"
#USAGE flag "--threshold <threshold>" help="Color difference threshold (from 0 to 1). Less more precise" default="0.1"
set -eou pipefail

TEMP_DIR="$(mktemp -d)"
FILE_PATH_HTML="$TEMP_DIR/index.html"

cat >"$FILE_PATH_HTML" <<EOF
<html>
  <head>
    <style>
      body {
        font-family: monospace;
      }
      table {
        border-collapse: collapse;
        margin-bottom: 24em;
        overflow-x: auto;
        table-layout: fixed;
        width: 100%;
      }
      td img {
        height: auto;
        max-width: 100%;
      }
      th, td {
        border: 1px solid #ccc;
        padding: 10px;
        text-align: center;
      }
    </style>
  </head>
  <body>
EOF

for FILE_PATH in $(git diff --name-only $usage_parent -- $usage_path); do
  if [ ! -f "$FILE_PATH" ]; then
    continue
  fi
  FILE_PATH_THIS="${FILE_PATH/.png/.this.png}"
  FILE_PATH_PREV="${FILE_PATH/.png/.prev.png}"
  FILE_PATH_DIFF="${FILE_PATH/.png/.diff.png}"
  echo "Processing $FILE_PATH"
  mkdir -p "$TEMP_DIR/$(dirname "$FILE_PATH_THIS")"
  git cat-file --filters "$usage_parent":"$FILE_PATH" > "$TEMP_DIR/$FILE_PATH_PREV" || {
    echo "warning: Could not retrieve the previous version of $FILE_PATH"
  }
  cp "$FILE_PATH" "$TEMP_DIR/$FILE_PATH_THIS"
  if ! aube exec odiff -t $usage_threshold --diff-mask "$TEMP_DIR/$FILE_PATH_PREV" "$TEMP_DIR/$FILE_PATH_THIS" "$TEMP_DIR/$FILE_PATH_DIFF"; then
    cat >>"$FILE_PATH_HTML" <<EOF
    <h2>$FILE_PATH</h2>
    <table>
      <tr>
        <th>OLD</th>
        <th>NEW</th>
        <th>DIFF</th>
      </tr>
      <tr>
        <td><img src="$FILE_PATH_PREV"></td>
        <td><img src="$FILE_PATH_THIS"></td>
        <td><img src="$FILE_PATH_DIFF"></td>
      </tr>
    </table>
EOF
  fi
done

cat >>"$FILE_PATH_HTML" <<EOF
  </body>
</html>
EOF

open "$FILE_PATH_HTML"
